[package]
name = "cocoa"
version = "0.1.0"
authors = ["Silvio Henrique Ferreira <shferreira@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objc = { path ="./rust-objc" }
libc = "*"
bitflags = "*"
